source 'http://rubygems.org'

gem 'facter', '>= 1.7.0'
gem 'oneview-sdk', '>= 3.0.0'
gem 'pry'
gem 'puppet', '>= 4.1'
gem 'puppet-lint', '>= 0.3.2'
gem 'puppetlabs_spec_helper', '>= 0.1.0'
gem 'rubocop', '= 0.46.0'
gem 'simplecov'
