################################################################################
# (C) Copyright 2020 Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

oneview_server_profile{'server_profile_present':
  ensure  => 'present',
  data    =>
  {
    name                  => 'Puppet Server Profile',
    serverHardwareTypeUri => 'SY 480 Gen9 1',
    enclosureGroupUri     => 'EG',
    enclosureBay          => 2,
    affinity              => 'BayAndServer',
    enclosureUri          => 'SGH537YCES',
    serialNumberType      => Virtual
    iscsiInitiatorNameType=> AutoGenerated
    macType               => Virtual
    wwnType               => Virtual
    description           => 'use case 1: boot from SAN'
    osDeploymentSettings  => {
      osDeploymentPlanUri => 'HPE - Developer 1.0 - Deployment Test (UEFI)'
    },
     boot                  =>
    {
      manageBoot        => true,
      order             =>
      [
      'CD',
      'USB',
      'HardDisk',
      'PXE'
      ],
      complianceControl => 'Checked'
    },
    bootMode              => {
      manageMode    => true,
      mode          => 'UEFIOptimized',
      pxeBootPolicy => 'Auto'
    },
    connections           => [{
      id            => 1,
      name          => 'deploy-network',
      functionType  => 'Ethernet',
      networkUri    => 'deploy',
      requestedMbps => 2500,
      requestedVFs  => 'Auto',
      boot          => {
        priority            => 'Primary',
        initiatorNameSource => 'ProfileInitiatorName'
      }
    }, {
      id            => 2,
      name          => 'corp',
      functionType  => 'Ethernet',
      networkUri    => 'mgmt',
      requestedMbps => 2500,
      requestedVFs  => 'Auto'
    }],
    bios                    => {
      manageBios: false
      overriddenSettings: []
    },
    hideUnusedFlexNics    => true
    iscsiInitiatorName    => ''
    localStorage            => {
      sasLogicalJBODs       => []
      controllers           => []
    },
    volumeAttachments     => [{     
      id            => 1,
      isBootVolume  => true,
      lunType       => Auto,
      storagePaths  => [{
        isEnabled           => true,
        connectionId        => 2
      },
        isEnabled           => true,
        connectionId        => 3
    }]
    volumeName              => win_boot,
    volumeStoragePoolName   => 'Pool name A'
}
oneview_server_hardware{'server_hardware_1':
    ensure => 'present',
    data   => {
      hostname        => '172.18.6.14',
      username        => 'dcs',
      password        => 'dcs',
      licensingIntent => 'OneView'
    },
}
oneview_server_hardware{'Server Hardware Power On':
    ensure => 'set_power_state',
    data   => {
      hostname    => '172.18.6.14',
      power_state => 'off',
    },
}