name: Puppet Rake test
on: [pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.3,2.4,2.5]
    runs-on: ${{ matrix.os }}
    steps:
    - name: git clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake

    - uses: codecov/codecov-action@v1
      with:
        flags: unit-test
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true