name: Build and publish to Puppet Forge

on:
 release:
  type: created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest tag
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Clone repository
      uses: actions/checkout@v1
      with:
        ref: ${{ env.RELEASE_VERSION }}
    - name: Build and publish module
      uses: barnumbirr/action-forge-publish@v2.3.0
      env:
       FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
       REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
    - name: Setup environment for Docker image publish
      run: |
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag hewlettpackardenterprise/hpe-oneview-sdk-for-puppet:${{ env.RELEASE_VERSION }}-OV5.4
    - name: Push the tagged Docker image
      run: docker push hewlettpackardenterprise/hpe-oneview-sdk-for-puppet:${{ env.RELEASE_VERSION }}-OV5.4
